name: game_boy_graphics_editor
description: Edit GBDK graphics source files

version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: ^5.0.0
  contextmenu: ^3.0.0
  image: ^3.2.0
  flutter_bloc: ^8.1.0
  replay_bloc: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Variable.ttf
